# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('btc_address', models.CharField(max_length=64)),
                ('hash_value', models.CharField(max_length=64)),
                ('payment_received', models.BooleanField()),
            ],
        ),
    ]
